rm(list = ls())

library(dlm)
library(dplyr)
library(here)
library(Metrics)
library(MARSS)
library(bayesdfa)
library(rstan)
library(bayesplot)

setwd("~/CBR/DLM_Analysis_Git")

cjs_raw<- readRDS("data/df_SAR_LGRLGA_MV.rds") 
#Remove NA at end of time series
Marine<- cjs_raw %>% select("CUI", "CUTI", "BEUTI", "Apr.mldno3", "SST_6mo")
Freshwater<- cjs_raw %>% select("mean.temp", "Annual.PNI", "mean.out")
dfa.marine.mat<- t(Marine)
dfa.freshwater.mat<- t(Freshwater)
cor.marine.dfa<- cor(Marine)

fit.marine1<- fit_dfa( y=dfa.marine.mat, num_trends=1, scale="zscore", iter=100000, chains=3, thin=1, cores=3)
saveRDS(fit.marine1, "marine1_DFA.rds")
fit.marine1<- readRDS("marine1_DFA.rds")
mcmc_trace(fit.marine1$samples, pars="Z[3,1]")
is_converged(fit.marine1, threshold=1.05)
rotated.marine1<- rotate_trends(fit.marine1)
Marine1_trends<- dfa_trends(rotated.marine1)
saveRDS(Marine1_trends, "marine1_trend.rds")
plot_trends(rotated.marine1)
plot_fitted(fit.marine1)
loo1<- loo(fit.marine1)
d<- dfa_loadings(rotated.marine1, summary=TRUE)


fit.marine2thin<- fit_dfa( y=dfa.marine.mat, num_trends=2, scale="zscore", iter=50000, warmup=25000, chains=3, thin=1, cores=3, varIndx = c(1,2,3,4,5), control=list(adapt_delta=0.999, max_treedepth=20))
saveRDS(fit.marine2150, "marine2adapt_DFA.rds")
fit.marine2<- readRDS("marine2_DFA.rds")
mcmc_trace(fit.marine2adapt$samples, pars="Z[3,1]")
is_converged(fit.marine2, threshold=1.05)
rotated<- rotate_trends(fit.text)
plot_trends(rotated)
plot_fitted(fit.text)
looM2<- loo(fit.marine2)
dfa_loadings(rotated, summary=TRUE)


fitFW1<- fit_dfa(y=dfa.freshwater.mat, num_trends=1, scale="zscore", iter=100000, chains=3, thin=1, cores=3, control=list(adapt_delta=0.999, max_treedepth=15))
saveRDS(fitFW1, "FW1_DFA.rds")
fitFW1<- readRDS("FW1_DFA.rds")
is_converged(fitFW1, threshold=1.05)
mcmc_trace(fit.text$samples, pars="Z[3,1]")
rotated.FW1<- rotate_trends(fitFW1)
FW1_trends<- dfa_trends(rotated.FW1)
saveRDS(FW1_trends, "FW1_trend.rds")
plot_trends(rotated.FW1)
plot_fitted(fitFW1)
loo2<- loo(fit2)
dfa_loadings(rotated.FW1, summary=TRUE)


fitFW2<- fit_dfa(y=dfa.freshwater.mat, num_trends=2, scale="zscore", iter=100000, chains=3, thin=1, cores=3, control=list(adapt_delta=0.999, max_treedepth=15))
saveRDS(fitFW2, "FW2_DFA.rds")
fitFW2<- readRDS("FW2_DFA.rds")
rotatedFW2<- rotate_trends(fitFW2)
FW2_trends<- dfa_trends(rotatedFW2)
saveRDS(FW2_trends, "FW2_trend.rds")
is_converged(fitFW2, threshold=1.05)
mcmc_trace(fitFW2$samples, pars="Z[3,1]")
plot_trends(rotatedFW2)
plot_fitted(fitFW2)
looFW2<- loo(fitFW2)
dfa_loadings(rotatedFW2, summary=TRUE)
